name: DenoEx CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SHELL: sh

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.4"
          otp-version: "25.1"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v2-
      - name: Install dependencies
        run: mix deps.get
      - name: Restore PLT cache
        id: plt_cache
        uses: actions/cache/restore@v3
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            priv/plts
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt
      - name: Save PLT cache
        id: plt_cache_save
        uses: actions/cache/save@v3
        if: steps.plt_cache.outputs.cache-hit != 'true'
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            priv/plts
      - name: Mix Formatter
        run: mix format --check-formatted
      - name: Check for compiler warnings
        run: mix compile --warnings-as-errors
      - name: Credo strict checks
        run: mix credo --strict
      - name: Doctor documentation checks
        run: mix doctor
      - name: Dialyzer checks
        run: mix dialyzer

  unit_test:
    name: Run ExUnit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir:
          - "1.14.4"
          - "1.15.4"
        otp:
          - "25.1"
          - "26.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 15
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v2-
      - name: Install dependencies
        run: mix deps.get
      - name: ExUnit tests
        env:
          MIX_ENV: test
          SHELL: /bin/bash
        run: mix coveralls.github
